BATCH_SIZE = 128

A_S_DEFAULT = 1
A_H_DEFAULT = 0.537634
B_H_DEFAULT = 0.930605

FITNESS_FUNC_DEFAULT = 'square'
MINIMIZATION_DEFAULT = True
POPULATION_SIZE_DEFAULT = 50
MAX_GENERATION_DEFAULT = 50
P_CROSSOVER_DEFAULT = 0.9
P_MUTATION_DEFAULT = 0.2
TOURN_SIZE_DEFAULT = 3
HALL_OF_FAME_SIZE_DEFAULT = 1
